// Kasiski Mandato 8 — painéis auditáveis, sem resultados de IA fabricados.
const intelUrl = (path='') => `/api/gabinetes/${S.gabineteId}/inteligencia${path}`;
async function intelTela(el){
 const [brief,fin,radar,check]=await Promise.all([api('GET',intelUrl('/briefing')),api('GET',intelUrl('/financeiro')),api('GET',intelUrl('/radar')),api('GET',intelUrl('/doublecheck'))]);
 const dinheiro=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 el.innerHTML=`<header class="cabecalho"><div><h1>Central de inteligência · 8.0</h1><p>Dados internos, histórico legislativo e conferência financeira.</p></div></header>
 <div class="intel-grid"><article><b>${brief.tarefas.length}</b><span>Tarefas com prazo em até 7 dias (inclui vencidas)</span></article><article><b>${brief.demandas.length}</b><span>Demandas com prazo em até 7 dias</span></article><article><b>${brief.agenda.length}</b><span>Compromissos próximos</span></article><article><b>${fin.com_alertas}</b><span>Emendas com alertas de conferência</span></article></div>
 <section class="intel-section"><h2>Radar legislativo versionado</h2><p>Registre textos oficiais e compare alterações. A captura é manual nesta versão.</p><form id="radar-form" class="intel-form"><input name="identificacao" required maxlength="160" placeholder="Identificação: PL 123/2026"><input name="fonte" placeholder="Fonte oficial"><input name="url" type="url" placeholder="URL da fonte"><input name="situacao" placeholder="Situação"><textarea name="ementa" placeholder="Ementa"></textarea><textarea name="texto" placeholder="Texto integral para comparação"></textarea><button type="submit">Adicionar proposição</button></form><div id="intel-radar">${radar.map(x=>`<article class="intel-item"><strong>${esc(x.identificacao)}</strong> <small>v${x.versao} · ${esc(x.situacao||'Situação não informada')}</small><p>${esc((x.ementa||'').slice(0,280))}</p>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Fonte</a>`:''} <button type="button" data-editar="${x.id}">Atualizar versão</button> <button type="button" data-comparar="${x.id}">Comparar</button></article>`).join('')||'<p>Nenhuma proposição cadastrada.</p>'}</div></section>
 <section class="intel-section"><h2>Conferência financeira</h2><p>${esc(fin.aviso)} Total pago registrado: <strong>${dinheiro(fin.total_pago)}</strong>.</p>${fin.registros.map(x=>`<article class="intel-item"><strong>${esc(x.objeto||x.numero||'Emenda')}</strong> · ${dinheiro(x.valores.pago)} pago<p>${x.alertas.length?x.alertas.map(a=>`<span class="intel-alert">${esc(a)}</span>`).join(''):'Sem divergências aritméticas detectadas.'}</p></article>`).join('')||'<p>Nenhuma emenda cadastrada.</p>'}</section>
 <section class="intel-section"><h2>Doublecheck — minutas existentes</h2><p>${esc(check.aviso)}</p>${check.minutas.map(x=>`<article class="intel-item"><a href="#/legislativo/${x.id}">${esc(x.titulo||'Minuta')}</a><p>${x.verificacao?esc(x.verificacao.comentario||'Verificação registrada; consulte o documento para os apontamentos.'):'Sem verificação registrada.'}</p></article>`).join('')||'<p>Nenhuma minuta cadastrada.</p>'}</section>
 <section class="intel-section"><h2>Briefing do gabinete</h2><p>${esc(brief.aviso)}</p><h3>Tarefas</h3>${brief.tarefas.map(x=>`<p>${esc(x.titulo)} — ${esc(x.prazo||'')}</p>`).join('')||'<p>Nenhuma tarefa próxima.</p>'}<h3>Demandas</h3>${brief.demandas.map(x=>`<p>${esc(x.titulo)} — ${esc(x.prazo||'')}</p>`).join('')||'<p>Nenhuma demanda próxima.</p>'}<h3>Agenda</h3>${brief.agenda.map(x=>`<p>${esc(x.titulo)} — ${esc(x.inicio||'')}</p>`).join('')||'<p>Sem compromissos próximos.</p>'}</section>`;
 el.querySelector('#radar-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await api('POST',intelUrl('/radar'),d);await intelTela(el)}catch(err){alert(err.message||'Erro ao salvar')}};
 el.querySelectorAll('[data-editar]').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.editar);const atual=await api('GET',intelUrl('/radar/'+id));const texto=prompt('Cole o texto da nova versão (cancelar mantém a versão):',atual.texto||'');if(texto===null)return;const situacao=prompt('Situação atual:',atual.situacao||'');if(situacao===null)return;await api('PUT',intelUrl('/radar/'+id),{texto,situacao});await intelTela(el)});
 el.querySelectorAll('[data-comparar]').forEach(b=>b.onclick=async()=>{const d=await api('GET',intelUrl('/radar/'+Number(b.dataset.comparar)+'/comparar'));const pre=document.createElement('pre');pre.className='intel-diff';pre.textContent=(d.diferencas||[]).join('\n')||d.mensagem||'Sem alterações';b.closest('article').appendChild(pre);b.disabled=true});
}
V.inteligencia=intelTela;
